version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: my-db
    
    environment:
      - PUID=1000
      - PGID=1000
    
    volumes:
      - ./database:/data/db
    
    ports:
      - 14999:14999
